encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:wiki_page>', views.fetch_wiki_page, name="fetch_wiki_page"),
    path('process_search/', views.process_search, name='process_search'),
    path('new_wiki_form/', views.new_wiki_form, name="new_wiki_form"),
    path('create_new_wiki', views.create_new_wiki, name='create_new_wiki' ),
    path('edit_wiki/<str:wiki_page>', views.edit_wiki, name='edit_wiki'),
    path('save_wiki_edit/<str:wiki_page>', views.save_wiki_edit, name='save_wiki_edit'),
    path('random_wiki', views.random_wiki, name="random_wiki")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('sandbox/', include('sandbox.urls'))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms

class wiki_search_form(forms.Form):
    search_term = forms.CharField(label='Search',
                                  initial = '',
                                  max_length = 20,
                                  widget = forms.TextInput(attrs={
                                      'name':'q',
                                      'class':'search',
                                      'placeholder':'Lookup Wiki'
                                  }))
#end wiki_search_form

class wiki_page_form(forms.Form):
    page_title = forms.CharField(label='Title',
                                 initial='',
                                 max_length=45,
                                 widget=forms.TextInput(attrs={
                                     'placeholder':'Enter The Name of The Wiki',
                                     'name': 'wiki_form_title',
                                     'class':'wiki_form_title_input'
                                 }))
    page_content=forms.CharField(label='',
                                 initial='',
                                 widget=forms.Textarea(attrs={
                                     'placeholder':'Enter wiki contents using Markdown',
                                     'name': 'page_content_textarea',
                                     'class': 'pagae_content_class',
                                     'cols': '10',
                                     'rows': '10'
                                 }))
#end wiki_page_form

encyclopedia/views.py
import http
import os
import os.path
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.core.files import File
import re
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import wiki_search_form, wiki_page_form
from . import util
from . import jefmcd2html



def index(request):
    print('########################################################')
    print('########################################################')
    print('#############    views.index        ####################')
    print('########################################################')
    print('########################################################')
    print('########################################################')

    if request.method == 'POST':
        pass
    else:
        search_form = wiki_search_form()
        return render(request, "encyclopedia/index.html", {
                        'heading': 'All Pages',
                        'search_form': search_form.as_p,
                        "entries": util.list_entries()
        })
# end index




def process_search(request):
    print('########################################################')
    print('########################################################')
    print('##########    views.process_search      ################')
    print('########################################################')
    print('########################################################')
    print('########################################################')
    
    def find_possible_matches(search_item):
        print(f"Search term = {search_item}")
        
        # Performing a Case Insensitive regex search
        # ie
        # search_term = 'th'
        # lst = ['OTher', 'tHiSTle', 'THIS', 'with']

        # Create a regex pattern with the search term ignoring case
        # pattern = re.compile(search_term, re.IGNORECASE)
        # Use list comprehension to filter the list based on the pattern
        # matching_items = [item for item in lst if re.search(pattern, item)]
        # print(matching_items)
        
        # Create a regex pattern with the search term ignoring case
        pattern = re.compile(search_item, re.IGNORECASE)
        
        # Use list comprehension to filter the list based on the pattern
        results =[entry for entry in wiki_pages if re.search(pattern, entry)]
        match_found = True
        if not results:
            match_found = False
            
        return match_found, results
    #end find_possible_matches
    
    """
        recieves request.POST from form submission
        extract search term from POST
        check reasonable variations of search_term against page list
        if entryfound rredirect to corrosponding page
        else redirect to Not Found Page
    """
    
    wiki_pages = util.list_entries()
    
    wiki_search = request.POST['search_term']
    page_found, wiki_search = util.check_page_exists(request.POST['search_term'])
    """
        At this point wiki_search will contain either
        1. A standardised page name eg they search for 'django' in the form. This is converted to 'Django'
        2. The user search tern wasnt found so wiki_search will get the same value back and be unchanged
    """

    if page_found:
        return HttpResponseRedirect(reverse('encyclopedia:fetch_wiki_page', args=(wiki_search,) ))
    else:
        match_found, entries = find_possible_matches(wiki_search)
        if not match_found:
            heading='Cant find a Wiki for '+wiki_search
            entries.append('Return to Main Page')
            search_form = wiki_search_form(request.POST)
            return render(request, 'encyclopedia/page_not_found.html', {
                        'heading': heading,
                        'search_form': search_form.as_p,
                        'entries': entries,
                        'page_request': wiki_search
            })
        #endif
        
        heading='Search Results'
        search_form = wiki_search_form()
        return render(request, 'encyclopedia/index.html', {
                        'heading': heading,
                        'search_form': search_form.as_p,
                        'entries': entries
        })
#end process_search






def fetch_wiki_page(request, wiki_page):
    """
    get list of all pages
    if requested page is in the list of wiki pagea
        get the markup from the file *** Do this in the template
        convert markup to HTML *** Do this in the template when rendering
        render wiki page
    else
        render not found page
    """
    print('########################################################')
    print('########################################################')
    print('#############    fetch_wiki_page    ####################')
    print('########################################################')
    print('########################################################')
    print('########################################################')


    # check_page_exists: returns page_not_found == True if page not in the entries directory
    # check_page_exists: returns the wiki_page as it is listed in the entries directory ie css will return CSS
    page_found, checked_page = util.check_page_exists(wiki_page)
    print(f'returned to fetch_page_wiki: \npage_found = {page_found}, \nchecked_page = {checked_page}\nrequested page = {wiki_page}')
 
    if page_found:#page exists, so open corrosponding wiki markdown page using the name from the wiki_page_lists
        # wiki_md = util.get_entry(checked_page)
        #covert markdown to html context
        print(f'##################### wiki_page => {wiki_page}',type(wiki_page))
        wiki_page_filename = checked_page + '.md'
        #wiki_html = util.new_markdown_to_html(wiki_md)
        wiki_html = jefmcd2html.translate_md2html(wiki_page_filename)
        print(f'returned to fetch_page_wiki: finished converting md to html')
        print(f'returned to fetch_page_wiki: about to render wiki_page with this content\n{wiki_html}')
        search_form = wiki_search_form()
        wiki_header_title = "<h1>Page Exists</h1>"
        #render the wiki page with the context
        return render(request, "encyclopedia/wiki_page.html", {
                            "wiki_header": wiki_header_title,
                            "wiki_page": checked_page,
                            "wiki_html": wiki_html,
                             "search_form": search_form.as_p
        })
    else: # requested page not found
        heading='Cant find a Wiki for ' + wiki_page
        entries='Return to Main Page'
        search_form = wiki_search_form()
        return render(request, 'encyclopedia/page_not_found.html', {
                    'heading': heading,
                    'search_form': search_form.as_p,
                    'entries': entries,
                    'page_request': wiki_page
        })
    #endif
        
# end fetch_wiki_page
    
    
    
def new_wiki_form(request):
    print('########################################################')
    print('########################################################')
    print('##########    views.new_wiki_form       ################')
    print('########################################################')
    print('########################################################')
    print('########################################################')
    new_wiki_form = wiki_page_form()
    search_form = wiki_search_form()
    return render(request, 'encyclopedia/load_new_wiki_form.html',{
                    'search_form': search_form.as_p,
                    'create_wiki_form': new_wiki_form.as_p,
                    'wiki_page': 'Create New Wiki'
    })


        
    
#end create_new_wiki

def create_new_wiki(request):
    print('########################################################')
    print('########################################################')
    print('##########    views.create_new_wiki     ################')
    print('########################################################')
    print('########################################################')
    print('########################################################')
    """
        get the request.POST and capture the wiki title and wiki body
        if page title already exists
            stay on page
            display error message
            allow user to correct error

        create a new file containing the body
        redirect to new page
    """
    title = request.POST['page_title']
    body = request.POST['page_content']
    wiki_search = default_storage.get_valid_name(title)
    # strip whitespaces and special characters from title
    
    # form the path to the target file to be created
    wiki_entries_location = 'entries/'
    wiki_root_path = os.path.dirname('.')
    wiki_entries_path = os.path.join(wiki_root_path, wiki_entries_location)
    target_file = wiki_entries_path + wiki_search + '.md'
    if(os.path.exists(target_file)):
        # If you need to delete file
        # os.remove(target_file)
        new_wiki_form = wiki_page_form(request.POST)
        search_form = wiki_search_form()
        return render(request, 'encyclopedia/load_new_wiki_form.html',{
                'search_form': search_form.as_p,
                'create_wiki_form': new_wiki_form.as_p,
                'wiki_page': 'Create New Wiki:<br> <h3>Title Already Exists. Select another</h3>'
        })
    else:

        new_wiki_file = open(target_file, 'wt')
        new_wiki_file.write(body)
        new_wiki_file.close
        
 
        
    if True:
        return HttpResponseRedirect(reverse('encyclopedia:fetch_wiki_page', args=(wiki_search,) ))
    else:
        return render(request, 'encyclopedia/test.html', {
                        'title': title,

encyclopedia/templates/encyclopedia/edit_wiki_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Wiki Page: {{wiki_page|safe}}
{% endblock %}

{% block body %}

    <!-- 
    """
        open the corrosponding wiki markdown file
        read contents
        populate a textarea
        save changes when save clicked
        redirect to new page
    """
    -->
    <div class='wiki_general edit_form'>
        <h2> Edit Wiki Page</h2>
        <form name='wiki_edit_form' action = "{% url 'encyclopedia:save_wiki_edit' wiki_page %}" method="POST">
            {% csrf_token %}
            {{edit_form|safe}}
            <div class="form_button">
                <input type="submit" name = "search-button" value="SAVE">
            </div>
        </form>
    </div>
    

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    

    <div class='wiki_general'>
        <h1>{{heading}}</h1>
        <ul class='wiki_index'>
            {% for entry in entries %}
                <li>
                    <a href="{% url 'encyclopedia:fetch_wiki_page' entry %}  ">{{entry}}
                </li>
            {% endfor %}
        </ul>
    </div>


{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title> {% block title %}
                {% endblock %}
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}?v2.9" rel="stylesheet">
    </head>
    <body>
        <div class="row">


            <div class="sidebar col-xl-2 col-lg-3 col-md-4">

                <div class="sidebar_contents">
                    <h1>Waki</h1>

                    <div class='search_form_box'>
                        <form name='wiki_search_form', id='wiki_search_form_id', action="{% url 'encyclopedia:process_search' %}", method='POST'>
                            {{search_form}}
                            <div class="form_button">
                                <input type="submit" class="search-btn" name = "search-button" value="Go!">
                            </div>
                            {% csrf_token %}
                        </form>
                    </div>
                    
                    <div class='sidebar_nav'>
                        <div>
                            <a href="{% url 'encyclopedia:index' %}">Home</a>
                        </div>
                        <div>
                            <a href="{% url 'encyclopedia:new_wiki_form' %}">New Page</a>
                        </div>
                        <div>
                            <a href="{% url 'encyclopedia:random_wiki' %}">Random</a>
                        </div>
                    </div>
      
                    {% block nav %}
                    {% endblock %}

                </div>

            </div>


            <div class="main col-xl-10 col-lg-9 col-md-8">
                <div class='right-panel'>
                    <div class='wikipage_header'>
                        <h2>Jef McD Project 1: Wiki</h2>
                    </div>
                    <div class='wiki_page'>
                        {% block body %}
                        {% endblock %}
                    </div>
                </div>

            </div>

        </div>


    </body>
</html>

encyclopedia/templates/encyclopedia/load_new_wiki_form.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki Page: {{wiki_page|safe}}
{% endblock %}

{% block body %}

    <!-- 
       Form for creating a New Wiki Page
       Input Box for title
       Input for Textarea
       Button to save the form
    -->
    <div class='wiki_general'>
        <h2>{{wiki_page|safe}}</h2>
    
        <form id="new_wiki_form_id" name="new_wiki_form" action="{% url 'encyclopedia:create_new_wiki' %}" method="POST"> 
            {% csrf_token %}   
            {{create_wiki_form|safe}}
            <div class="form_button">
                <input type="submit" class="search-btn" name = "search-button" value="Save">
            </div>
        </form>
    
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/page_not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki Page: Dont Know Anything About That - Sorry!
{% endblock %}

{% block body %}

    <!-- 
        open the corrosponding wiki file
        convert markdown to html
        render the html wiki_page
    -->
    <div class='page_not_found_main'>
        <div class = 'page_not_found'>
            <img src = '../../static/img/cant_find_circle.png' alt='wiki not found'>
        </div>
        <div class="not_found_explanation">
            <h3>I'm so sorry, but I cant seem to find {{page_request}}</h3>
            <br>Perhaps it is yet to be written? hmmm??
        <div>
    </div>



{% endblock %}

encyclopedia/templates/encyclopedia/test.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <title> test
        </title>
    </head>
    <body>
        <h1>New Wiki Data</h1>
        <div>Title : {{title}}</div>
        <br>
        <div>Body : {{body}}</div>
        <br>
        <div>Generated Valid Title : {{valid_title}}</div>
        <br>
        <div>Wiki Entries Path {{wiki_entries_path}}</div>
        <br>
        <div>Target File : {{target_file}}</div>
        <br>
        <div></div>
        <br>
        <div></div>
        <br>
    </body>
</html>

encyclopedia/templates/encyclopedia/wiki_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki Page: {{wiki_header|safe}}
{% endblock %}

{% block body %}

    <!-- 
        open the corrosponding wiki file
        convert markdown to html
        render the html wiki_page
    -->
    <div class='wiki_general'>
        <div>{{wiki_html|safe}}</div>
        <br>
    </div>
    <div class="edit_btn_flexbox">
        <div class='edit_wiki_btn'>
            <a href="{% url 'encyclopedia:edit_wiki' wiki_page %}">Edit Page</a>
        </div>
    </div>

    

{% endblock %}